config/routes.rb
Evented::Application.routes.draw do
  resources :advice_contents
  
  resources :advice_content_advices, :controller => 'advice_contents'
  resources :advice_content_roots, :controller => 'advice_contents'

  resources :secondary_prereqs

  resources :filters

  devise_for :users
  
  resources :chosen_parameters

  resources :chosen_tools

  resources :parameter_values

  resources :parameter_types

  resources :parameters

  resources :pre_tool_associations

  resources :tools

  resources :contents
  
  resources :content_texts, :controller => 'contents'
  resources :content_choices, :controller => 'contents'
  resources :content_effects, :controller => 'contents'
  resources :content_outcomes, :controller => 'contents'

  resources :probabilities
  
  resources :users

  resources :chosen_filters
  
  resources :chosen_outcomes
  
  resources :secondary_chosen_outcomes
  
  resources :secondary_prereqs

  resources :events do
    get 'download', on: :collection
  end

  root 'events#index'

  

end

app/models/content.rb
class Content < ActiveRecord::Base
  
  has_ancestry
  
  validates :condition, :inclusion => Probability::CONDITIONS, :allow_blank => true
  validates :equality1, :inclusion => Probability::EQUALITY_MARKERS_WITH_RANGE, :allow_blank => true
  validates :equality2, :inclusion => Probability::EQUALITY_MARKERS, :allow_blank => true
  validates :andor, :inclusion => Probability::ANDOR, :allow_blank => true
  
  belongs_to :tool1, :class_name => "ChosenTool", :inverse_of => :content_tool1, :dependent => :destroy
  belongs_to :tool2, :class_name => "ChosenTool", :inverse_of => :content_tool2, :dependent => :destroy
  
  accepts_nested_attributes_for :tool1, :allow_destroy => true
  accepts_nested_attributes_for :tool2, :allow_destroy => true
  
  before_save :clear_fields
  
  private
  
  def clear_fields
    if !self.new_record? && self.type != 'ContentEffect'
      if self.condition.blank?
        unless tool1.nil?
          self.tool1.tool = nil
          self.tool1.pre_tool = nil
          self.tool1.save
        end
        unless tool2.nil?
          self.tool2.tool = nil
          self.tool2.pre_tool = nil
          self.tool2.save
        end
        self.equality1 = nil
        self.equality2 = nil
        self.value1 = nil
        self.value2 = nil
        self.andor = nil
        self.rangevalue = nil
      else
        if self.tool1.tool && self.tool1.tool.booleanreturn
          self.equality1 = nil
          self.value1 = nil
        end
        if self.tool2.tool && self.tool2.tool.booleanreturn
          self.equality2 = nil
          self.value2 = nil
        end
        if self.equality1 == 'range'
          unless tool2.nil?
            self.tool2.tool = nil
            self.tool2.pre_tool = nil
            self.tool2.save
          end
          self.equality2 = nil
          self.value2 = nil
          self.andor = nil
        elsif self.andor.blank?
          unless tool2.nil?
            self.tool2.tool = nil
            self.tool2.pre_tool = nil
            self.tool2.save
          end
          self.equality2 = nil
          self.value2 = nil
        end
      end
      
      if self.equality1 != 'range'
        self.rangevalue = nil
      end
    end
  end
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.build_tool1
    if @content.type != 'ContentEffect' 
      @content.build_tool2
    end
    @event = @content.root.event
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.js   { flash[:notice] = "Content was successfully created" }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    @event = @content.root.event
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully saved.' }
        format.js   { flash[:notice] = "Content was successfully saved" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @event = @content.root.event
    @id = @content.id
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url }
      format.js   { flash[:notice] = "Content was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:ancestry, :type, :text, :condition, :tool1_id, :skill1_id, :equality1, :value1, :andor, :tool2_id, :skill2_id, :equality2, :value2, :event_id, :rangevalue, :parent_id,
                                      :tool1_attributes => [:id, :tool_id, :pre_tool_id, :chosen_parameters_attributes => [:id, :chosen_tool_id, :parameter_value_id, :custom_value, :parameter_id]],
                                      :tool2_attributes => [:id, :tool_id, :pre_tool_id, :chosen_parameters_attributes => [:id, :chosen_tool_id, :parameter_value_id, :custom_value, :parameter_id]])
    end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ancestry %><br>
    <%= f.text_field :ancestry %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :tool1 %><br>
    <%= f.number_field :tool1 %>
  </div>
  <div class="field">
    <%= f.label :skill1 %><br>
    <%= f.number_field :skill1 %>
  </div>
  <div class="field">
    <%= f.label :equality1 %><br>
    <%= f.text_field :equality1 %>
  </div>
  <div class="field">
    <%= f.label :andor %><br>
    <%= f.text_field :andor %>
  </div>
  <div class="field">
    <%= f.label :tool2 %><br>
    <%= f.number_field :tool2 %>
  </div>
  <div class="field">
    <%= f.label :skill2 %><br>
    <%= f.number_field :skill2 %>
  </div>
  <div class="field">
    <%= f.label :equality2 %><br>
    <%= f.text_field :equality2 %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/create.js.erb
var newhtml = "<%= escape_javascript(render(:partial => '/events/event_content_rows', :locals => { :content_row => @content } )) %>";

var $newhtml = $(newhtml);

$newhtml.find('.content_row').hide();

$newhtml.find('.content_dropdown, .content_text_field, .content_text').each(function() {
   var $field = $(this);
   if ($field.val() == '')
   {
       $field.css('background-color', '#FFCCCC');
   }
});

$('#ajaxcontentmarker').replaceWith($newhtml);

$newhtml.find('.content_row').fadeIn(200);

<% if @content.type == 'ContentChoice' %>
  <% if @content.sibling_choices_before_this.any? %>
    $newhtml.prev().addClass('content_branch_choice');
  <% end %>
<% end %>

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/contents/destroy.js.erb
$('input#content_id').each(function() {
	if ($(this).val() === '<%= @id %>')
	{
		var $branch = $(this).closest('.content_branch');
		$branch.stop().fadeOut(200);
		setTimeout(function() {
			$branch.remove();
		}, 200);
	}
});

<% if @content.type == 'ContentChoice' %>
  <% if @content.sibling_choices_after_this.count == 0 %>
  	<% if @content.sibling_choices_before_this.any? %>
    	$newhtml.prev().removeClass('content_branch_choice', 200);
    <% end %>
  <% end %>
  
  var advicehtml = "<%= escape_javascript(render :partial => '/events/event_advice_block' ) %>";
  var $advicehtml = $(advicehtml);
  $advicehtml.find('.advice_dropdown, .advice_text_field, .advice_text').each(function() {
	var $field = $(this);
	if ($field.val() == '')
   	{
    	$field.css('background-color', '#FFCCCC');
    }
  });
  $('#event_advice_block').replaceWith($advicehtml);
<% end %>

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
    <tr>
      <th>Ancestry</th>
      <th>Type</th>
      <th>Text</th>
      <th>Condition</th>
      <th>Tool1</th>
      <th>Skill1</th>
      <th>Equality1</th>
      <th>Andor</th>
      <th>Tool2</th>
      <th>Skill2</th>
      <th>Equality2</th>
      <th>Event</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.ancestry %></td>
        <td><%= content.type %></td>
        <td><%= content.text %></td>
        <td><%= content.condition %></td>
        <td><%= content.tool1 %></td>
        <td><%= content.skill1 %></td>
        <td><%= content.equality1 %></td>
        <td><%= content.andor %></td>
        <td><%= content.tool2 %></td>
        <td><%= content.skill2 %></td>
        <td><%= content.equality2 %></td>
        <td><%= content.event_id %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ancestry:</strong>
  <%= @content.ancestry %>
</p>

<p>
  <strong>Type:</strong>
  <%= @content.type %>
</p>

<p>
  <strong>Text:</strong>
  <%= @content.text %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @content.condition %>
</p>

<p>
  <strong>Tool1:</strong>
  <%= @content.tool1 %>
</p>

<p>
  <strong>Skill1:</strong>
  <%= @content.skill1 %>
</p>

<p>
  <strong>Equality1:</strong>
  <%= @content.equality1 %>
</p>

<p>
  <strong>Andor:</strong>
  <%= @content.andor %>
</p>

<p>
  <strong>Tool2:</strong>
  <%= @content.tool2 %>
</p>

<p>
  <strong>Skill2:</strong>
  <%= @content.skill2 %>
</p>

<p>
  <strong>Equality2:</strong>
  <%= @content.equality2 %>
</p>

<p>
  <strong>Event:</strong>
  <%= @content.event_id %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/contents/update.js.erb
<% if @content.type == 'ContentText' %>
	var newhtml = "<%= escape_javascript(render(:partial => '/events/event_content_text_form', :locals => { :content_text => @content } )) %>";
<% elsif @content.type == 'ContentChoice' %>
	var newhtml = "<%= escape_javascript(render(:partial => '/events/event_content_choice_form', :locals => { :content_choice => @content } )) %>";
	var advicehtml = "<%= escape_javascript(render :partial => '/events/event_advice_block' ) %>";
  	var $advicehtml = $(advicehtml);
  	$advicehtml.find('.advice_dropdown, .advice_text_field, .advice_text').each(function() {
		var $field = $(this);
		if ($field.val() == '')
	   	{
	    	$field.css('background-color', '#FFCCCC');
	    }
  	});
  	$('#event_advice_block').replaceWith($advicehtml);
<% elsif @content.type == 'ContentOutcome' %>
	var newhtml = "<%= escape_javascript(render(:partial => '/events/event_content_outcome_form', :locals => { :content_outcome => @content } )) %>";
<% elsif @content.type == 'ContentEffect' %>
	var newhtml = "<%= escape_javascript(render(:partial => '/events/event_content_effect_form', :locals => { :content_effect => @content } )) %>";
<% end %>

var $newhtml = $(newhtml);

$newhtml.find('.content_dropdown, .content_text_field, .content_text').each(function() {
   var $field = $(this);
   if ($field.val() == '')
   {
       $field.css('background-color', '#FFCCCC');
   }
});

var $contentrow = $("input[value='<%= @content.id %>'].content_id_for_ancestry").closest(".content_row");

$contentrow.replaceWith($newhtml);

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);