config/routes.rb
Evented::Application.routes.draw do
  resources :advice_contents
  
  resources :advice_content_advices, :controller => 'advice_contents'
  resources :advice_content_roots, :controller => 'advice_contents'

  resources :secondary_prereqs

  resources :filters

  devise_for :users
  
  resources :chosen_parameters

  resources :chosen_tools

  resources :parameter_values

  resources :parameter_types

  resources :parameters

  resources :pre_tool_associations

  resources :tools

  resources :contents
  
  resources :content_texts, :controller => 'contents'
  resources :content_choices, :controller => 'contents'
  resources :content_effects, :controller => 'contents'
  resources :content_outcomes, :controller => 'contents'

  resources :probabilities
  
  resources :users

  resources :chosen_filters
  
  resources :chosen_outcomes
  
  resources :secondary_chosen_outcomes
  
  resources :secondary_prereqs

  resources :events do
    get 'download', on: :collection
  end

  root 'events#index'

  

end

app/models/secondary_prereq.rb
class SecondaryPrereq < ActiveRecord::Base
  belongs_to :event
  belongs_to :prereq, :class_name => 'Event'
  has_many :secondary_chosen_outcomes, :dependent => :destroy
  
  accepts_nested_attributes_for :secondary_chosen_outcomes, :allow_destroy => true
  
  attr_accessor :secondary_chosen_outcome_id
  
  before_save :mark_secondary_chosen_outcomes_for_removal
  
  def get_available_secondary_outcomes
    outcomes = []
    unless self.prereq_id.blank?
      self.prereq.content_root.descendants.where(:type => 'ContentEffect').each do |effect|
        if effect.tool1 && effect.tool1.tool.name == 'end'
          outcomes << effect.parent
        end
      end
      remove_outcomes = []
      self.event.secondary_prereqs.each do |secondary_prereq|
        secondary_prereq.secondary_chosen_outcomes.each do |secondary_chosen_outcome|
          remove_outcomes << secondary_chosen_outcome.content_outcome
        end
      end
      if self.prereq == self.event.parent && self.event.chosen_outcomes.any?
        endoutcomes = []
        self.event.parent.content_root.descendants.where(:type => 'ContentEffect').each do |effect|
          if effect.tool1 && effect.tool1.tool.name == 'end'
            endoutcomes << effect.parent
          end
        end
        chosenoutcomes = []
        ChosenOutcome.where(:event_id => event.id).each do |outcome|
          if event.parent.id == outcome.content_outcome.root.event.id
            chosenoutcomes << outcome.content_outcome
          end
        end
        remove_outcomes += (endoutcomes - chosenoutcomes)
      end
      outcomes = outcomes - remove_outcomes
    end
    return outcomes
  end
  
  def mark_secondary_chosen_outcomes_for_removal
    if self.prereq_id.blank?
      puts 'AAAAAAAAAAAAAAAAAAAAAAAARGH 2'
      self.secondary_chosen_outcomes.each do |secondary_chosen_outcome|
        secondary_chosen_outcome.mark_for_destruction
        puts 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGH 3 ' + secondary_chosen_outcome.marked_for_destruction?.to_s
      end
    else
      self.secondary_chosen_outcomes.each do |secondary_chosen_outcome|
        secondary_chosen_outcome.mark_for_destruction if secondary_chosen_outcome.content_outcome_id.blank?
        secondary_chosen_outcome.mark_for_destruction if secondary_chosen_outcome.content_outcome.root.event_id != secondary_chosen_outcome.secondary_prereq.prereq_id
      end
    end
  end
  
end

app/controllers/secondary_prereqs_controller.rb
class SecondaryPrereqsController < ApplicationController
  before_action :set_secondary_prereq, only: [:show, :edit, :update, :destroy]

  # GET /secondary_prereqs
  # GET /secondary_prereqs.json
  def index
    @secondary_prereqs = SecondaryPrereq.all
  end

  # GET /secondary_prereqs/1
  # GET /secondary_prereqs/1.json
  def show
  end

  # GET /secondary_prereqs/new
  def new
    @secondary_prereq = SecondaryPrereq.new
  end

  # GET /secondary_prereqs/1/edit
  def edit
  end

  # POST /secondary_prereqs
  # POST /secondary_prereqs.json
  def create
    @secondary_prereq = SecondaryPrereq.new(secondary_prereq_params)
    @event = Event.find params[:secondary_prereq][:event_id]

    respond_to do |format|
      if @secondary_prereq.save
        format.html { redirect_to @secondary_prereq, notice: 'Secondary prereq was successfully created.' }
        format.js   { flash[:notice] = "Event link was successfully created" }
        format.json { render action: 'show', status: :created, location: @secondary_prereq }
      else
        format.html { render action: 'new' }
        format.json { render json: @secondary_prereq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondary_prereqs/1
  # PATCH/PUT /secondary_prereqs/1.json
  def update
    @event = Event.find @secondary_prereq.event_id
    unless params[:secondary_prereq][:secondary_chosen_outcome_id].blank?
      @secondary_prereq.secondary_chosen_outcomes << SecondaryChosenOutcome.new(:secondary_prereq_id => @secondary_prereq.id, :content_outcome_id => params[:secondary_prereq][:secondary_chosen_outcome_id])
      puts 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ' + params[:secondary_prereq][:secondary_chosen_outcome_id]
      params[:secondary_prereq][:secondary_chosen_outcome_id] = nil
    end
    respond_to do |format|
      if @secondary_prereq.update(secondary_prereq_params)
        format.html { redirect_to @secondary_prereq, notice: 'Secondary prereq was successfully updated.' }
        format.js   { flash[:notice] = "Event link was successfully updated" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @secondary_prereq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondary_prereqs/1
  # DELETE /secondary_prereqs/1.json
  def destroy
    @event = Event.find @secondary_prereq.event_id
    @secondary_prereq.destroy
    respond_to do |format|
      format.html { redirect_to secondary_prereqs_url }
      format.js   { flash[:notice] = "Event link was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondary_prereq
      @secondary_prereq = SecondaryPrereq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondary_prereq_params
      params.require(:secondary_prereq).permit(:event_id, :prereq_id, :p, :secondary_chosen_outcome_id)
    end
end

app/helpers/secondary_prereqs_helper.rb
module SecondaryPrereqsHelper
end

app/views/secondary_prereqs/_form.html.erb
<%= form_for(@secondary_prereq) do |f| %>
  <% if @secondary_prereq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secondary_prereq.errors.count, "error") %> prohibited this secondary_prereq from being saved:</h2>

      <ul>
      <% @secondary_prereq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :prereq_id %><br>
    <%= f.number_field :prereq_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secondary_prereqs/create.js.erb
$('#event_secondary_prereq_form').html("<%= escape_javascript(render(:partial => '/events/event_secondary_prereq_rows')) %>");

$('#event_secondary_prereq_form').find('.secondary_prereq_event, .secondary_prereq_p').each(function() {
	$field = $(this);
	if ($field.val() === '')
	{
		$field.css('background-color', '#FFCCCC');
	}
});

$("form[action='/secondary_prereqs/<%= @secondary_prereq.id %>']").parents('.row').hide().fadeIn(200);

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/secondary_prereqs/destroy.js.erb
$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/secondary_prereqs/edit.html.erb
<h1>Editing secondary_prereq</h1>

<%= render 'form' %>

<%= link_to 'Show', @secondary_prereq %> |
<%= link_to 'Back', secondary_prereqs_path %>

app/views/secondary_prereqs/index.html.erb
<h1>Listing secondary_prereqs</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Prereq</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @secondary_prereqs.each do |secondary_prereq| %>
      <tr>
        <td><%= secondary_prereq.event_id %></td>
        <td><%= secondary_prereq.prereq_id %></td>
        <td><%= link_to 'Show', secondary_prereq %></td>
        <td><%= link_to 'Edit', edit_secondary_prereq_path(secondary_prereq) %></td>
        <td><%= link_to 'Destroy', secondary_prereq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secondary prereq', new_secondary_prereq_path %>

app/views/secondary_prereqs/new.html.erb
<h1>New secondary_prereq</h1>

<%= render 'form' %>

<%= link_to 'Back', secondary_prereqs_path %>

app/views/secondary_prereqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @secondary_prereq.event_id %>
</p>

<p>
  <strong>Prereq:</strong>
  <%= @secondary_prereq.prereq_id %>
</p>

<%= link_to 'Edit', edit_secondary_prereq_path(@secondary_prereq) %> |
<%= link_to 'Back', secondary_prereqs_path %>

app/views/secondary_prereqs/update.js.erb
$('#event_secondary_prereq_form').html("<%= escape_javascript(render(:partial => '/events/event_secondary_prereq_rows')) %>");

$('#event_secondary_prereq_form').find('.secondary_prereq_event, .secondary_prereq_p').each(function() {
	$field = $(this);
	if ($field.val() === '')
	{
		$field.css('background-color', '#FFCCCC');
	}
});

<% builder = ActionView::Helpers::FormBuilder.new(:event, @event, self, {}) %>

var outcomehtml = "<%= escape_javascript(render(:partial => '/events/event_pre_form', :locals => { :f => builder })) %>";

var $outcomehtml = $(outcomehtml);

$('#prereq_cell').replaceWith($outcomehtml);

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);