config/routes.rb
Evented::Application.routes.draw do
  resources :advice_contents
  
  resources :advice_content_advices, :controller => 'advice_contents'
  resources :advice_content_roots, :controller => 'advice_contents'

  resources :secondary_prereqs

  resources :filters

  devise_for :users
  
  resources :chosen_parameters

  resources :chosen_tools

  resources :parameter_values

  resources :parameter_types

  resources :parameters

  resources :pre_tool_associations

  resources :tools

  resources :contents
  
  resources :content_texts, :controller => 'contents'
  resources :content_choices, :controller => 'contents'
  resources :content_effects, :controller => 'contents'
  resources :content_outcomes, :controller => 'contents'

  resources :probabilities
  
  resources :users

  resources :chosen_filters
  
  resources :chosen_outcomes
  
  resources :secondary_chosen_outcomes
  
  resources :secondary_prereqs

  resources :events do
    get 'download', on: :collection
  end

  root 'events#index'

  

end

app/models/probability.rb
class Probability < ActiveRecord::Base
  
  CONDITIONS = ['if']
  EQUALITY_MARKERS = ['<', '<=', '=', '>=', '>', 'NOT']
  EQUALITY_MARKERS_WITH_RANGE = ['<', '<=', '=', '>=', '>', 'NOT', 'range']
  ANDOR = ['AND', 'OR']
  
  validates :p, :presence => true
  validates :condition, :inclusion => CONDITIONS, :allow_blank => true
  validates :equality1, :inclusion => EQUALITY_MARKERS_WITH_RANGE, :allow_blank => true
  validates :equality2, :inclusion => EQUALITY_MARKERS, :allow_blank => true
  validates :andor, :inclusion => ANDOR, :allow_blank => true
  belongs_to :event
  belongs_to :tool1, :class_name => "ChosenTool", :inverse_of => :probability_tool1, :dependent => :destroy
  belongs_to :tool2, :class_name => "ChosenTool", :inverse_of => :probability_tool2, :dependent => :destroy
  
  accepts_nested_attributes_for :tool1, :allow_destroy => true
  accepts_nested_attributes_for :tool2, :allow_destroy => true
  
  before_save :clear_fields
  
  private
  
  def clear_fields
    unless self.new_record?
      if self.condition.blank?
        unless tool1.nil?
          self.tool1.tool = nil
          self.tool1.pre_tool = nil
          self.tool1.save
        end
        unless tool2.nil?
          self.tool2.tool = nil
          self.tool2.pre_tool = nil
          self.tool2.save
        end
        self.equality1 = nil
        self.equality2 = nil
        self.value1 = nil
        self.value2 = nil
        self.andor = nil
        self.rangevalue = nil
      else
        if self.tool1.tool && self.tool1.tool.booleanreturn
          self.equality1 = nil
          self.value1 = nil
        end
        if self.tool2.tool && self.tool2.tool.booleanreturn
          self.equality2 = nil
          self.value2 = nil
        end
        if self.equality1 == 'range'
          unless tool2.nil?
            self.tool2.tool = nil
            self.tool2.pre_tool = nil
            self.tool2.save
          end
          self.equality2 = nil
          self.value2 = nil
          self.andor = nil
        elsif self.andor.blank?
          unless tool2.nil?
            self.tool2.tool = nil
            self.tool2.pre_tool = nil
            self.tool2.save
          end
          self.equality2 = nil
          self.value2 = nil
        end
      end
      if self.equality1 != 'range'
        self.rangevalue = nil
      end
    end
  end
  
end

app/controllers/probabilities_controller.rb
class ProbabilitiesController < ApplicationController
  before_action :set_probability, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin!

  # GET /probabilities
  # GET /probabilities.json
  def index
    @probabilities = Probability.all
  end

  # GET /probabilities/1
  # GET /probabilities/1.json
  def show
  end

  # GET /probabilities/new
  def new
    @probability = Probability.new
  end

  # GET /probabilities/1/edit
  def edit
  end

  # POST /probabilities
  # POST /probabilities.json
  def create
    @probability = Probability.new(probability_params)
    @probability.build_tool1
    @probability.build_tool2
    @event = Event.find params[:probability][:event_id]

    respond_to do |format|
      if @probability.save
        format.html { redirect_to @probability, notice: 'Event was successfully saved' }
        format.js   { flash[:notice] = "Probability was successfully created" }
        format.json { render action: 'show', status: :created, location: @probability }
      else
        format.html { render action: 'new' }
        format.json { render json: @probability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /probabilities/1
  # PATCH/PUT /probabilities/1.json
  def update
    @event = Event.find @probability.event_id
    respond_to do |format|
      if @probability.update(probability_params)
        format.html { redirect_to @probability, notice: 'Event was successfully saved' }
        format.js   { flash[:notice] = "Probability was successfully saved" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @probability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probabilities/1
  # DELETE /probabilities/1.json
  def destroy
    @event = Event.find @probability.event_id
    @probability.destroy
    respond_to do |format|
      format.html { redirect_to probabilities_url }
      format.js   { flash[:notice] = "Probability was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probability
      @probability = Probability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def probability_params
      params.require(:probability).permit(:condition, :tool1_id, :equality1, :value1, :andor, :tool2_id, :equality2, :value2, :p, :event_id, :rangevalue,
                                          :tool1_attributes => [:id, :tool_id, :pre_tool_id, :chosen_parameters_attributes => [:id, :chosen_tool_id, :parameter_value_id, :custom_value, :parameter_id]],
                                          :tool2_attributes => [:id, :tool_id, :pre_tool_id, :chosen_parameters_attributes => [:id, :chosen_tool_id, :parameter_value_id, :custom_value, :parameter_id]])
    end
    
    def is_admin!
      if current_user.admin
        true
      else
        redirect_to events_path, notice: "You don't have rights to view the page you requested."
      end
    end
end

app/helpers/probabilities_helper.rb
module ProbabilitiesHelper
end

app/views/probabilities/_form.html.erb
<%= form_for(@probability) do |f| %>
  <% if @probability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@probability.errors.count, "error") %> prohibited this probability from being saved:</h2>

      <ul>
      <% @probability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :tool1 %><br>
    <%= f.text_field :tool1 %>
  </div>
  <div class="field">
    <%= f.label :equality1 %><br>
    <%= f.text_field :equality1 %>
  </div>
  <div class="field">
    <%= f.label :value1 %><br>
    <%= f.text_field :value1 %>
  </div>
  <div class="field">
    <%= f.label :andor %><br>
    <%= f.text_field :andor %>
  </div>
  <div class="field">
    <%= f.label :tool2 %><br>
    <%= f.text_field :tool2 %>
  </div>
  <div class="field">
    <%= f.label :equality2 %><br>
    <%= f.text_field :equality2 %>
  </div>
  <div class="field">
    <%= f.label :value2 %><br>
    <%= f.text_field :value2 %>
  </div>
  <div class="field">
    <%= f.label :p %><br>
    <%= f.text_field :p %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/probabilities/create.js.erb
$('#event_probability_form').html("<%= escape_javascript(render(:partial => '/events/event_probability_rows')) %>");

$('#event_probability_form').find('.probability_dropdown, .probability_text_field').each(function() {
	$field = $(this);
	if ($field.val() === '')
	{
		$field.css('background-color', '#FFCCCC');
	}
});

$("form[action='/probabilities/<%= @probability.id %>']").parents('.row').hide().fadeIn(200);

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/probabilities/destroy.js.erb
$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);

app/views/probabilities/edit.html.erb
<h1>Editing probability</h1>

<%= render 'form' %>

<%= link_to 'Show', @probability %> |
<%= link_to 'Back', probabilities_path %>

app/views/probabilities/index.html.erb
<h1>Listing probabilities</h1>

<table>
  <thead>
    <tr>
      <th>Condition</th>
      <th>Tool1</th>
      <th>Equality1</th>
      <th>Value1</th>
      <th>Andor</th>
      <th>Tool2</th>
      <th>Equality2</th>
      <th>Value2</th>
      <th>P</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @probabilities.each do |probability| %>
      <tr>
        <td><%= probability.condition %></td>
        <td><%= probability.tool1 %></td>
        <td><%= probability.equality1 %></td>
        <td><%= probability.value1 %></td>
        <td><%= probability.andor %></td>
        <td><%= probability.tool2 %></td>
        <td><%= probability.equality2 %></td>
        <td><%= probability.value2 %></td>
        <td><%= probability.p %></td>
        <td><%= link_to 'Show', probability %></td>
        <td><%= link_to 'Edit', edit_probability_path(probability) %></td>
        <td><%= link_to 'Destroy', probability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Probability', new_probability_path %>

app/views/probabilities/new.html.erb
<h1>New probability</h1>

<%= render 'form' %>

<%= link_to 'Back', probabilities_path %>

app/views/probabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Condition:</strong>
  <%= @probability.condition %>
</p>

<p>
  <strong>Tool1:</strong>
  <%= @probability.tool1 %>
</p>

<p>
  <strong>Equality1:</strong>
  <%= @probability.equality1 %>
</p>

<p>
  <strong>Value1:</strong>
  <%= @probability.value1 %>
</p>

<p>
  <strong>Andor:</strong>
  <%= @probability.andor %>
</p>

<p>
  <strong>Tool2:</strong>
  <%= @probability.tool2 %>
</p>

<p>
  <strong>Equality2:</strong>
  <%= @probability.equality2 %>
</p>

<p>
  <strong>Value2:</strong>
  <%= @probability.value2 %>
</p>

<p>
  <strong>P:</strong>
  <%= @probability.p %>
</p>

<%= link_to 'Edit', edit_probability_path(@probability) %> |
<%= link_to 'Back', probabilities_path %>

app/views/probabilities/update.js.erb
var newhtml = "<%= escape_javascript(render(:partial => '/events/event_probability_form', :locals => { :probability => @probability })) %>";

var $newhtml = $(newhtml);

$newhtml.find('.probability_dropdown, .probability_text_field').each(function() {
	$field = $(this);
	if ($field.val() === '')
	{
		$field.css('background-color', '#FFCCCC');
	}
});

var $probabilitycell = $("form[action='/probabilities/<%= @probability.id %>']").closest(".cell");

$probabilitycell.replaceWith($newhtml);

$('#infobox').html("<%= escape_javascript(render(:partial => '/events/infobox')) %>");

$('#edit_notices').css('opacity', 1)
				  .fadeTo(2000, 0);