config/routes.rb
Evented::Application.routes.draw do
  resources :advice_contents
  
  resources :advice_content_advices, :controller => 'advice_contents'
  resources :advice_content_roots, :controller => 'advice_contents'

  resources :secondary_prereqs

  resources :filters

  devise_for :users
  
  resources :chosen_parameters

  resources :chosen_tools

  resources :parameter_values

  resources :parameter_types

  resources :parameters

  resources :pre_tool_associations

  resources :tools

  resources :contents
  
  resources :content_texts, :controller => 'contents'
  resources :content_choices, :controller => 'contents'
  resources :content_effects, :controller => 'contents'
  resources :content_outcomes, :controller => 'contents'

  resources :probabilities
  
  resources :users

  resources :chosen_filters
  
  resources :chosen_outcomes
  
  resources :secondary_chosen_outcomes
  
  resources :secondary_prereqs

  resources :events do
    get 'download', on: :collection
  end

  root 'events#index'

  

end

app/models/parameter_value.rb
class ParameterValue < ActiveRecord::Base
  
  validates_uniqueness_of :name, :scope => [:parameter_type_id]
  
  belongs_to :parameter_type
  has_many :chosen_parameters, :dependent => :destroy
  
end

app/controllers/parameter_values_controller.rb
class ParameterValuesController < ApplicationController
  before_action :set_parameter_value, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin!

  # GET /parameter_values
  # GET /parameter_values.json
  def index
    @parameter_values = ParameterValue.all
  end

  # GET /parameter_values/1
  # GET /parameter_values/1.json
  def show
  end

  # GET /parameter_values/new
  def new
    @parameter_value = ParameterValue.new
  end

  # GET /parameter_values/1/edit
  def edit
  end

  # POST /parameter_values
  # POST /parameter_values.json
  def create
    @parameter_value = ParameterValue.new(parameter_value_params)

    respond_to do |format|
      if @parameter_value.save
        format.html { redirect_to @parameter_value, notice: 'Parameter value was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parameter_value }
      else
        format.html { render action: 'new' }
        format.json { render json: @parameter_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parameter_values/1
  # PATCH/PUT /parameter_values/1.json
  def update
    respond_to do |format|
      if @parameter_value.update(parameter_value_params)
        format.html { redirect_to @parameter_value, notice: 'Parameter value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parameter_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parameter_values/1
  # DELETE /parameter_values/1.json
  def destroy
    @parameter_value.destroy
    respond_to do |format|
      format.html { redirect_to parameter_values_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parameter_value
      @parameter_value = ParameterValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameter_value_params
      params.require(:parameter_value).permit(:parameter_type_id, :name, :tooltip)
    end
    
    def is_admin!
      if current_user.admin
        true
      else
        redirect_to events_path, notice: "You don't have rights to view the page you requested."
      end
    end
end

app/helpers/parameter_values_helper.rb
module ParameterValuesHelper
end

app/views/parameter_values/_form.html.erb
<%= form_for(@parameter_value) do |f| %>
  <% if @parameter_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parameter_value.errors.count, "error") %> prohibited this parameter_value from being saved:</h2>

      <ul>
      <% @parameter_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parameter_type_id %><br>
    <%= f.number_field :parameter_type_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parameter_values/edit.html.erb
<h1>Editing parameter_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @parameter_value %> |
<%= link_to 'Back', parameter_values_path %>

app/views/parameter_values/index.html.erb
<h1>Listing parameter_values</h1>

<table>
  <thead>
    <tr>
      <th>Parameter type</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parameter_values.each do |parameter_value| %>
      <tr>
        <td><%= parameter_value.parameter_type_id %></td>
        <td><%= parameter_value.name %></td>
        <td><%= link_to 'Show', parameter_value %></td>
        <td><%= link_to 'Edit', edit_parameter_value_path(parameter_value) %></td>
        <td><%= link_to 'Destroy', parameter_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parameter value', new_parameter_value_path %>

app/views/parameter_values/new.html.erb
<h1>New parameter_value</h1>

<%= render 'form' %>

<%= link_to 'Back', parameter_values_path %>

app/views/parameter_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parameter type:</strong>
  <%= @parameter_value.parameter_type_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @parameter_value.name %>
</p>

<%= link_to 'Edit', edit_parameter_value_path(@parameter_value) %> |
<%= link_to 'Back', parameter_values_path %>